//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_ibm_bios_H
#define METASPRITE_ibm_bios_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ibm_bios_TILE_ORIGIN 0
#define ibm_bios_TILE_W 8
#define ibm_bios_TILE_H 8
#define ibm_bios_WIDTH 128
#define ibm_bios_HEIGHT 128
#define ibm_bios_TILE_COUNT 256
#define ibm_bios_PALETTE_COUNT 1
#define ibm_bios_COLORS_PER_PALETTE 4
#define ibm_bios_TOTAL_COLORS 4
#define ibm_bios_MAP_ATTRIBUTES 0

BANKREF_EXTERN(ibm_bios)

extern const palette_color_t ibm_bios_palettes[4];
extern const uint8_t ibm_bios_tiles[4096];

extern const unsigned char ibm_bios_map[256];
#define ibm_bios_map_attributes ibm_bios_map

#endif
